export const retirementObjFour = {
    id: 'retirementinfo',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '은퇴 정보',
    headline: '은퇴에 되해서 더 알아보세요!',
    description: '의퇴의 문제점 과 만족스러운 은테 하는 방법들 알아보세요',
    buttonLabel: '시작',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: "Life Coaching",
    dark: false,
    primary: false,
    darkText: true,
};