export const homeObjOne = {
    id: 'coachinginfo',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: '코칭 정보',
    headline: '다양한 코칭에 되해서 더 알아보세요!',
    description: '커리어 코칭, 임원 코칭, 직원 코칭',
    buttonLabel: '시작',
    imgStart: true,
    img: require('../../images/svg-1.svg').default,
    alt: "코칭 정보",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'mentoringinfo',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '멘토링 정보',
    headline: '멘토링이 정확히 뭔지 알아보세요!',
    description: '멘토링을 하면서 도움을 얻을 수 있습니다!',
    buttonLabel: '시작',
    imgStart: false,
    img: require('../../images/svg-2.svg').default,
    alt: "Life Coaching",
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'leadershipinfo',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: '리더십 정보',
    headline: '리더십에 되해서 더 알아보세요!',
    description: '어떢에 하면 리더십을 더 가질수 있을까요?',
    buttonLabel: '시작',
    imgStart: true,
    img: require('../../images/svg-3.svg').default,
    alt: "Life Coaching",
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjFour = {
    id: 'retirementinfo',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '은퇴 정보',
    headline: '은퇴에 되해서 더 알아보세요!',
    description: '의퇴의 문제점 과 만족스러운 은테 하는 방법들 알아보세요',
    buttonLabel: '시작',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: "Life Coaching",
    dark: false,
    primary: false,
    darkText: true,
};